# Generated by Django 5.2.12 on 2026-04-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_ext',
            new_name='question_text',
        ),
    ]
